<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\assets\js\aos.js" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\assets\js\aos.js" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\assets\images\icon\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\assets\js\aos.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Cors" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\assets\fonts\fa-solid-900.ttf">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
